# Generated by Django 2.2.8 on 2019-12-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
